### ISSUE TITLE
Client-side code on server side

### ISSUE THREAD

**Issue by iarspider** [BigXplosion/ShieldHider#1]
Crash report:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-beta-40.jar)
  LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  IC2core (industrialcraft-2-2.6.1-ex110.jar)
  FMLPlugin (InventoryTweaks-1.61-beta-57.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 7/11/16 8:14 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/ItemMeshDefinition
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:562)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/ItemMeshDefinition
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:485)
    at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:235)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:213)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:531)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.ItemMeshDefinition
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 29 more
Caused by: java.lang.ArrayIndexOutOfBoundsException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 851298528 bytes (811 MB) / 1627914240 bytes (1552 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 2 total; -Xms1G -Xmx3G
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.0.2007 115 mods loaded, 115 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader] (forge.jar) 
    UC  Forge{12.18.0.2007} [Minecraft Forge] (forge.jar) 
    UC  ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10-alpha-1.0.0.jar) 
    UC  JEI{3.7.5.227} [Just Enough Items] (jei_1.10.2-3.7.5.227.jar) 
    UC  abyssalcraft{1.9.2.1} [AbyssalCraft] (AbyssalCraft-1.10-1.9.2.1.jar) 
    UC  actuallyadditions{1.10.2-r49} [Actually Additions] (ActuallyAdditions-1.10.2-r49.jar) 
    UC  AppleCore{1.3.5} [AppleCore] (AppleCore-mc1.10.2-1.3.5.jar) 
    UC  armorplus{1.9.4-4.0.1.0} [ArmorPlus] (ArmorPlus1.9.4-4.0.1.0.jar) 
    UC  autopackager{1.6.3} [AutoPackager] (autopackager-1.6.3.jar) 
    UC  bagginses{2.4.2d} [Bagginses] (Bagginses-1.10-3.0.1a.jar) 
    UC  Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
    UC  BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
    UC  bdlib{1.12.0.2} [BD Lib] (bdlib-1.12.0.2-mc1.10.2.jar) 
    UC  betteragriculture{0.16} [Better Agriculture] (BetterAgriculture_(MC-1.10)-0.16.jar) 
    UC  BiomesOPlenty{4.1.0.2033} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2033-universal.jar) 
    UC  BloodMagic{1.9.4-2.0.2-48} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.2-48.jar) 
    UC  Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.9.4-1.4.1.jar) 
    UC  bookshelf{1.2.3.279} [Bookshelf] (Bookshelf-1.9.4-1.2.3.279.jar) 
    UC  Botania{r1.8-312} [Botania] (Botania-unofficial.r1.8-312.jar) 
    UC  Chameleon{1.9.4-2.1.5} [Chameleon] (Chameleon-1.9.4-2.1.5.jar) 
    UC  mcmultipart{1.2.0} [MCMultiPart] (MCMultiPart-1.2.0-universal.jar) 
    UC  CharsetLib{0.3.0-pre12} [вЂЅ] (Charset-0.3.0-pre12.jar) 
    UC  CharsetAudio{0.3.0-pre12} [в™«] (Charset-0.3.0-pre12.jar) 
    UC  CharsetCarts{0.3.0-pre12} [U] (Charset-0.3.0-pre12.jar) 
    UC  CharsetDecoration{0.3.0-pre12} [вљ?] (Charset-0.3.0-pre12.jar) 
    UC  CharsetDrama{0.3.0-pre12} [!] (Charset-0.3.0-pre12.jar) 
    UC  CharsetFarming{0.3.0-pre12} [;] (Charset-0.3.0-pre12.jar) 
    UC  CharsetGates{0.3.0-pre12} [&] (Charset-0.3.0-pre12.jar) 
    UC  CharsetPipes{0.3.0-pre12} [|] (Charset-0.3.0-pre12.jar) 
    UC  CharsetStorage{0.3.0-pre12} [#] (Charset-0.3.0-pre12.jar) 
    UC  CharsetTweaks{0.3.0-pre12} [*] (Charset-0.3.0-pre12.jar) 
    UC  CharsetWires{0.3.0-pre12} [+] (Charset-0.3.0-pre12.jar) 
    UC  CharsetWrench{0.3.0-pre12} [/] (Charset-0.3.0-pre12.jar) 
    UC  chisel{@VERSION@} [Chisel] (Chisel-MC1.9.4-0.0.5.29.jar) 
    UC  chiselsandbits{11.5} [Chisels & Bits] (chiselsandbits-11.5.jar) 
    UC  cookingforblockheads{3.1.26} [Cooking for Blockheads] (CookingForBlockheads-mc1.9.4-3.1.26.jar) 
    UC  correlatedpotentialistics{1.1.2} [Correlated Potentialistics] (CorrelatedPotentialistics-1.1.2.jar) 
    UC  craftingtweaks{5.0.6} [Crafting Tweaks] (craftingtweaks-mc1.9.4-5.0.6.jar) 
    UC  MineTweaker3{3.0.10} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.10.jar) 
    UC  DarkUtils{1.1.2.52} [Dark Utilities] (DarkUtilities-1.9.4-1.1.2.55.jar) 
    UC  ElecCore{1.5.292} [ElecCore] (ElecCore-1.9.4-1.5.292.jar) 
    UC  deepresonance{1.2.0beta35} [DeepResonance] (deepresonance-1.9.4-1.2.0beta35.jar) 
    UC  easyBreeding{5.0.0} [Easy Breeding] (easybreeding-1.9.4-4.0.1.jar) 
    UC  EnderBags{2.0.1} [EnderBags] (EnderBags-1.9.4-2.0.0.jar) 
    UC  endercore{1.10-0.4.0.33-alpha} [EnderCore] (EnderCore-1.10-0.4.0.33-alpha.jar) 
    UC  EnderIO{1.10-3.0.0.55_alpha} [Ender IO] (EnderIO-1.10-3.0.0.55_alpha.jar) 
    UC  shetiphiancore{3.2.6} [ShetiPhian-Core] (shetiphiancore-1.9.4-3.2.6.jar) 
    UC  endertanks{1.3.6} [EnderTanks] (endertanks-1.9.4-1.3.6.jar) 
    UC  enderthing{0.6.8} [Enderthing] (enderthing-1.9.4-0.6.8.jar) 
    UC  EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
    UC  endmetals{1.0.4} [End Metals] (EndMetals_1.9-1.0.4.jar) 
    UC  ValkyrieLib{1.10-0.10.0} [Valkyrie Lib] (valkyrielib-1.10-0.10.0.jar) 
    UC  EnvironmentalTech{1.10-0.10.0b} [Environmental Tech] (environmentaltech-1.10-0.10.0b.jar) 
    UC  FastLeaveDecay{1.1} [Fast Leave Decay] (FastLeaveDecay-MC1.9.4-1.2.1.jar) 
    UC  flatcoloredblocks{mc1.10-v4.1} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.1.jar) 
    UC  forestry{5.1.10.192} [Forestry] (forestry_1.10.2-5.1.10.192.jar) 
    UC  ftbl{2.1.0} [FTBLib] (FTBLib-1.9.4-2.1.0-pre2.jar) 
    UC  ftbu{2.1.0} [FTBUtilities] (FTBUtilities-1.9.4-2.1.0-pre2.jar) 
    UC  IC2{2.6.1-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.1-ex110.jar) 
    UC  gendustry{1.6.4.7} [GenDustry] (gendustry-1.6.4.7-mc1.10.2.jar) 
    UC  advgenerators{0.9.20.4} [Advanced Generators] (generators-0.9.20.4-mc1.10.2.jar) 
    UC  fishing{1.4} [Fishing Net Mod] (GiacomosFishingNet1.9.4-1.4.jar) 
    UC  grapple_hooks{1.0.8} [Grapple Hooks] (GrappleHooks-1.10-1.0.8.jar) 
    UC  Harvest{1.9.4-1.0.1-8} [Harvest] (Harvest-1.9.4-1.0.1-8.jar) 
    UC  InfernalMobs{1.7.1} [Infernal Mobs] (InfernalMobs-1.10.jar) 
    UC  inventorytweaks{1.61-beta-57-c028bbc} [Inventory Tweaks] (InventoryTweaks-1.61-beta-57.jar) 
    UC  IronChest{7.0.6.794} [Iron Chest] (ironchest-1.10.2-7.0.6.794.jar) 
    UC  journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
    UC  mantle{1.10-0.10.3.jenkins156} [Mantle] (Mantle-1.10-0.10.3.jar) 
    UC  Mekanism{9.1.0} [Mekanism] (MekanismAll-1.10-9.1.0.homebaked.jar) 
    UC  MekanismGenerators{9.1.0} [MekanismGenerators] (MekanismAll-1.10-9.1.0.homebaked.jar) 
    UC  MekanismTools{9.1.0} [MekanismTools] (MekanismAll-1.10-9.1.0.homebaked.jar) 
    UC  testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
    UC  Morphtool{GRADLE:VERSION-GRADLE:BUILD} [Morph-o-Tool] (Morph-o-Tool-1.0-4.jar) 
    UC  Morpheus{1.10-3.1.6} [Morpheus] (Morpheus-1.10-3.1.6.jar) 
    UC  NashornLib{1.9.4-1.8.77-1.3.1} [Nashorn Library] (NashornLib-1.9.4-1.8.77-1.3.1.8.jar) 
    UC  nethermetals{1.1.2} [Nether Metals] (NetherMetals_1.9-1.1.2.jar) 
    UC  netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
    UC  nmsot{1.1.5-mc1.10} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.1.5-mc1.10.jar) 
    UC  notenoughwands{1.3.5} [Not Enough Wands] (notenoughwands-1.9.4-1.3.5.jar) 
    UC  OpenComputers{1.6.0.2-beta.4} [OpenComputers] (OpenComputers-MC1.10-1.6.0.2-beta.4.jar) 
    UC  fodc{1.9.0} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.0.jar) 
    UC  orespawn{1.0.3} [Ore Spawn] (OreSpawn_1.9.4-1.0.3.jar) 
    UC  packingtape{0.5.2} [Packing Tape] (PackingTape-1.9.4-0.5.2.jar) 
    UC  harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4c.jar) 
    UC  Pillar{GRADLE:VERSION-GRADLE:BUILD} [Pillar] (Pillar-1.0-2.jar) 
    UC  platforms{1.1.4} [Platforms] (platforms-1.9.4-1.1.4.jar) 
    UC  progressiveautomation{1.6.48} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.48.jar) 
    UC  Psi{r1.0-36} [Psi] (Psi-r1.0-36.jar) 
    UC  Quark{beta-40} [Quark] (Quark-beta-40.jar) 
    UC  randomthings{3.7.4} [Random Things] (RandomThings-MC1.10-3.7.4.jar) 
    UC  StorageDrawers{1.9.4-3.1.11} [Storage Drawers] (StorageDrawers-1.9.4-3.1.11.jar) 
    UC  refinedstorage{0.8.5} [Refined Storage] (refinedstorage-0.8.5.jar) 
    UC  xreliquary{1.10.2-1.3.2.419} [Reliquary] (Reliquary-1.10.2-1.3.2.419.jar) 
    UC  rftools{5.02} [RFTools] (rftools-1.10-5.02.jar) 
    UC  rftoolsdim{4.30beta45} [RFTools Dimensions] (rftoolsdim-1.10-4.30beta45.jar) 
    UC  Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
    UC  roots{0.107} [Roots] (roots-0.107.jar) 
    UC  shadowmc{3.4.1} [ShadowMC] (ShadowMC-1.10.2-3.4.1.jar) 
    UE  ShieldHider{1.0.1} [Shield Hider] (ShieldHider-1.0.1_1.9.4.jar) 
    UC  simpleretrogen{4.0.1+8} [Simple Retrogen] (simpleretrogen-1.10-4.0.1+8.jar) 
    UC  SleepingBag{1.2.1} [Sleeping Bag] (SleepingBag-1.9.4-1.2.1.jar) 
    UC  solarvillage{1.1.0.13} [Solar Village] (SolarVillage-1.10-1.1.0.14.jar) 
    UC  soulshardstow{1.10-2.5.0-34} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10-2.5.0-34.jar) 
    UC  SpiceOfLife{1.3.3} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.3.jar) 
    UC  substratum{1.6.0.1} [Substratum] (Substratum-1.10.2-1.6.0.1.jar) 
    UC  tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
    UC  Tesla{1.1.0.24} [TESLA] (Tesla-1.9.4-1.1.0.24.jar) 
    UC  theoneprobe{1.0.13} [The One Probe] (theoneprobe-1.10-1.0.13.jar) 
    UC  tombmanygraves{1.9.4-2.1.6} [Tomb Many Graves] (TombManyGraves-1.9.4-2.1.6.jar) 
    UC  vc{v0.2.9b-mc1.10.2} [ViesCraft] (ViesCraft-0.2.9b-mc1.10.2.jar) 
    UC  waterstrainer{1.0.0a} [Water Strainer] (WaterStrainer-1.10.2-1.0.0a.jar) 
    UC  weaponsplus{1.9.4-3.0.0.0} [WeaponsPlus] (WeaponsPlus1.9.4-3.0.0.0.jar) 
    UC  xprings{1.1.0} [Experience Rings] (xprings-1.1.0.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-beta-40.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  lumien.randomthings.asm.ClassTransformer
AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  squeek.applecore.asm.TransformerModuleHandler
IC2core (industrialcraft-2-2.6.1-ex110.jar)

FMLPlugin (InventoryTweaks-1.61-beta-57.jar)
  invtweaks.forge.asm.ContainerTransformer
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)

    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)
```

**Comment by BigXplosion** [comment]
Well the mod isn't supposed to be installed on the server. But I might change the setup so that the mod will load correctly on the server even though it won't do anything there.

P.S. Sorry for the late response but I was on vacation.
